apiVersion: 1
prune: true

datasources:
  - name: logicalDB
    type: postgres
    access: proxy
    orgId: 1
    uid: logicalDB
    url: database:5432
    user: ${POSTGRES_USER}
    isDefault: true
    jsonData:
      connMaxLifetime: 14400
      database: ${POSTGRES_DB}
      maxIdleConns: 100
      maxIdleConnsAuto: true
      maxOpenConns: 100
      postgresVersion: 1700
      sslmode: disable
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    version: 1
    editable: true
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    uid: loki
    url: ${LOKI_URL}
    isDefault: false
    version: 1
    editable: true