{
 "title": "TheLogicalDashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "system_functions",
    "query": {}
   },
   {
    "name": "integration_functions",
    "query": {}
   },
   {
    "name": "id",
    "query": "SELECT id FROM \"Relations\" LIMIT 1000"
   }
  ]
 },
 "panels": [
  {
   "title": "Log Volume by Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(service) (rate({service=~\"system-api|freightCompany|warehouseCompany\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "System API Functions Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(function) (rate({service=\"system-api\"} [$__interval]))"
    }
   ]
  },
  { "title": "Relations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Order: $id",
   "type": "table",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT * from \"Relations\" WHERE id = '$id' limit 1"
    }
   ]
  },
  {
   "title": "Total Relations",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as count FROM \"Relations\""
    }
   ]
  },
  {
   "title": "logging for relation: $id",
   "type": "logs",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 21 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{id=\"$id\"} | line_format ` {{__timestamp__}} - {{.service}} - {{.function}} - {{__line__}}`"
    }
   ]
  },
  {
   "title": "system relations",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT * FROM \"Relations\" WHERE owner = 'system' LIMIT 10"
    }
   ]
  },
  {
   "title": "freightCompany",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT * FROM \"Relations\" WHERE owner = 'freightCompany' LIMIT 10"
    }
   ]
  },
  {
   "title": "warehouseCompany",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "rawSql": "SELECT * FROM \"Relations\" WHERE owner = 'warehouseCompany' LIMIT 10"
    }
   ]
  },
  {
   "title": "Integrations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "$integration_functions function logs",
     "type": "logs",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 47 },
     "repeat": "integration_functions",
     "targets": [
      {
       "direction": "backward",
       "expr": "{service=\"warehouseCompany\"} | line_format `{{__timestamp__}} - ({{.function}}) - {{__line__}}`"
      }
     ]
    },
    {
     "title": "$integration_functions function logs",
     "type": "logs",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 63 },
     "repeat": "integration_functions",
     "targets": [
      {
       "direction": "backward",
       "expr": "{service=\"freightCompany\"} | line_format `{{__timestamp__}} - ({{.function}}) - {{__line__}}`"
      }
     ]
    }
   ]
  },
  {
   "title": "Platform api",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "$system_functions function logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 144 },
     "repeat": "system_functions",
     "targets": [
      {
       "direction": "backward",
       "expr": "{service=\"system-api\", function=\"$system_functions\"} | line_format `({{.function}}) - {{__line__}} - {{__timestamp__}}`"
      }
     ]
    }
   ]
  }
 ]
}